In [2]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[-0.74063701 -0.41785221  1.26371408  0.51253307  1.25816247]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.74063701 -0.41785221  1.26371408  0.51253307  1.25816247]


In [6]:
print(np.dot(a, a.T))

4.16577986736


In [7]:
a  = np.random.randn(5,1)
print(a)

[[-0.47378201]
 [-0.65727164]
 [-0.15895989]
 [-1.21132858]
 [-0.08997601]]


In [8]:
print(a.T)

[[-0.47378201 -0.65727164 -0.15895989 -1.21132858 -0.08997601]]


In [9]:
print(np.dot(a, a.T))

[[ 0.22446939  0.31140348  0.07531233  0.57390569  0.04262902]
 [ 0.31140348  0.43200601  0.10447983  0.79617193  0.05913868]
 [ 0.07531233  0.10447983  0.02526825  0.19255266  0.01430258]
 [ 0.57390569  0.79617193  0.19255266  1.46731694  0.10899052]
 [ 0.04262902  0.05913868  0.01430258  0.10899052  0.00809568]]


In [10]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

In [11]:
print(image.shape)

(3, 3, 2)


In [12]:
image.shape[0]

3

In [13]:
v = image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))

In [14]:
v

array([[ 0.67826139],
       [ 0.29380381],
       [ 0.90714982],
       [ 0.52835647],
       [ 0.4215251 ],
       [ 0.45017551],
       [ 0.92814219],
       [ 0.96677647],
       [ 0.85304703],
       [ 0.52351845],
       [ 0.19981397],
       [ 0.27417313],
       [ 0.60659855],
       [ 0.00533165],
       [ 0.10820313],
       [ 0.49978937],
       [ 0.34144279],
       [ 0.94630077]])

In [15]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

In [16]:
x_norm = np.linalg.norm(x, ord = 2, axis = 1, keepdims = True)

In [17]:
print(x_norm.shape)

(2, 1)


In [18]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])

In [19]:
x_exp = np.exp(x)
x_exp

array([[  8.10308393e+03,   7.38905610e+00,   1.48413159e+02,
          1.00000000e+00,   1.00000000e+00],
       [  1.09663316e+03,   1.48413159e+02,   1.00000000e+00,
          1.00000000e+00,   1.00000000e+00]])

In [26]:
x_sum = np.sum(x, axis = 1, keepdims = True)
x_sum.shape

(2, 1)

In [25]:
x / x_sum

array([[ 0.5625    ,  0.125     ,  0.3125    ,  0.        ,  0.        ],
       [ 0.58333333,  0.41666667,  0.        ,  0.        ,  0.        ]])