In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249763.160326
Vectorized version:5406.309127807617ms
249763.160326
For loop:561.0320568084717ms


In [3]:
cc = a * b.T
cc.shape

(1000000,)

In [4]:
t1 = np.log(1)
t1

0.0

In [5]:
A = np.array([0.1,0.2,0.6])
A

array([ 0.1,  0.2,  0.6])

In [6]:
B = np.array(A > 0.1, dtype=np.int64)
B

array([0, 1, 1], dtype=int64)

In [7]:
w = np.zeros([2,4])
w

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c = a * b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [9]:
c = np.random.randn(4, 3) * 0.01


In [10]:
c

array([[-0.01568242,  0.00148091, -0.00953519],
       [-0.01190857,  0.00510038,  0.00508905],
       [ 0.00387586,  0.00517573, -0.00303126],
       [-0.01000528,  0.0232319 , -0.00745234]])

In [11]:
c = np.zeros(4,1)
c

TypeError: data type not understood

In [13]:
A = np.random.randn(1,3)
B = np.random.randn(1,3)
print(A)
print(B)

[[ 0.15198617  1.15458522  1.45399999]]
[[-2.22940928 -1.90341202  0.27920833]]


In [14]:
cost = np.dot(B, np.log(A).T)

In [15]:
print(cost)

[[ 4.03104492]]


In [16]:
cost = np.asscalar(cost)

In [17]:
cost


4.031044922669592

In [18]:
cost = [[ 0.69291989]]


In [19]:
print(cost)


[[0.69291989]]


In [20]:
test = np.squeeze(cost)

In [21]:
print(test)


0.69291989


In [28]:
assert(isinstance(test, list))

AssertionError: 