In [2]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

250201.208046
Vectorized version:782.0446491241455ms
250201.208046
For loop:566.0324096679688ms


In [4]:
cc = a * b.T
cc.shape

(1000000,)

In [5]:
t1 = np.log(1)
t1

0.0

In [6]:
A = np.array([0.1,0.2,0.6])
A

array([ 0.1,  0.2,  0.6])

In [7]:
B = np.array(A > 0.1, dtype=np.int64)
B

array([0, 1, 1], dtype=int64)

In [9]:
w = np.zeros([2,4])
w

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])